---
# tasks file for ansible-role-nis

- include_tasks: install.yml
  when: nis_enabled and ansible_os_family == "RedHat"
- include_tasks: initialize.yml
  when: nis_initialize and ansible_os_family == "RedHat"

